[versions]
androidxJunit = "1.3.0"
composeMarkdown = "0.3.6"
espressoCoreVersion = "3.7.0"
hiltAndroidTesting = "2.48"
hiltAndroidCompiler = "2.48"
hiltAndroidTestingVersion = "2.48"
kotlinxCoroutinesTest = "1.10.1"
kotlinxSerializationJson = "1.8.0"
ktorClientAndroid = "3.1.2"
ktorClientContentNegotiationJvm = "3.1.2"
ktorClientCore = "3.1.2"
ktorClientLogging = "3.1.2"
ktorClientMock = "2.2.3"
ktorClientMockJvm = "3.1.2"
ktorSerializationKotlinxJsonJvm = "3.1.2"
library = "8.0.2"
agp = "8.7.3"
kotlin = "2.0.0"
coreKtx = "1.15.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
lifecycleRuntimeKtx = "2.10.0"

activityCompose = "1.9.3"
composeBom = "2026.02.00"

#Generative AI SDK
generativeai = "0.9.0"

#
material = "1.13.0"
constraintlayout = "2.2.1"
androidx-appcompat = "1.7.1"
materialVersion = "1.10.3"
mockkAndroid = "1.14.2"
multidex = "2.0.1"

#Accompanist
accompanist-permissions = "0.31.0-alpha"
accompanist-webview = "0.24.11-rc"
accompanist-drawablepainter = "0.32.0"
accompanist-flowlayout = "0.31.0-alpha"
accompanist-systemuicontroller = "0.30.1"
accompanist-pager = "0.25.0"
accompanist-pager-indicators = "0.25.0"
commons-io = "2.13.0"

#PDFium
pdfium-android = "1.9.0"
android-pdf-viewer = "3.2.0-beta.1"

# Compose
navigation-compose = "2.9.7"
protolite-well-known-types = "18.0.1"
constraintlayout-compose = "1.1.1"

#Dagger-Hilt
hilt = "2.54"
hilt-work = "1.3.0"
hilt-compose = "1.3.0"

#Activity KTX for viewModels()
activity-ktx = "1.9.3"

# Glide
glide = "4.15.1"

#Lifecycle
lifecycle-version = "2.10.0"
robolectric = "4.14"
runtime-livedata = "1.10.3"
lifecycle-extensions = "2.2.0"

#Retrofit2
retrofit = "2.11.0"
okhttp = "5.0.0-alpha.11"

#Coroutines
coroutines = "1.10.2"

#Room Database
room = "2.8.4"

#Splash
core-splashscreen = "1.2.0"

#Data Store
datastore-preferences = "1.2.0"

#In App Purchase
billing-version = "8.3.0"
firebase-crashlytics-buildtools = "3.0.6"

#Firebase
gms-play-services-ads = "24.9.0"

#Lottie Animation
lottie-compose = "4.0.0"

#Coil Image Loading
coil = "2.5.0"

#Html Text Viewer
compose-html = "1.0.2"

#Itext PDF
itext7-core = "7.2.5"
slf4j-simple = "2.0.7"

#Shimmer
shimmer = "0.5.0"

#JSoup for HTML parsing
jsoup = "1.15.4"

#Download File
startupRuntime = "1.2.0"
truth = "1.4.4"
ui = "1.10.3"
work-runtime-ktx = "2.11.1"

#KSP
ksp = "1.9.20-1.0.14"
navigationTesting = "2.9.7"
core = "1.52.0"


[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-espresso-core-v351 = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCoreVersion" }
androidx-junit-v115 = { module = "androidx.test.ext:junit", version.ref = "androidxJunit" }
androidx-startup-runtime = { module = "androidx.startup:startup-runtime", version.ref = "startupRuntime" }
compose-markdown = { module = "com.github.jeziellago:compose-markdown", version.ref = "composeMarkdown" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hiltAndroidCompiler" }
hilt-android-testing = { module = "com.google.dagger:hilt-android-testing", version.ref = "hiltAndroidTesting" }
hilt-android-testing-v244 = { module = "com.google.dagger:hilt-android-testing", version.ref = "hiltAndroidTestingVersion" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }

#Generative AI SDK
#add the dependency for the Google AI client SDK for Android


kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutinesTest" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
ktor-client-android = { module = "io.ktor:ktor-client-android", version.ref = "ktorClientAndroid" }
ktor-client-content-negotiation-jvm = { module = "io.ktor:ktor-client-content-negotiation-jvm", version.ref = "ktorClientContentNegotiationJvm" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktorClientCore" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktorClientLogging" }
ktor-client-mock = { module = "io.ktor:ktor-client-mock", version.ref = "ktorClientMock" }
ktor-client-mock-jvm = { module = "io.ktor:ktor-client-mock-jvm", version.ref = "ktorClientMockJvm" }
ktor-serialization-kotlinx-json-jvm = { module = "io.ktor:ktor-serialization-kotlinx-json-jvm", version.ref = "ktorSerializationKotlinxJsonJvm" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidx-appcompat" }
mockk-android = { module = "io.mockk:mockk-android", version.ref = "mockkAndroid" }
truth = { module = "com.google.truth:truth", version.ref = "truth" }
ui = { module = "androidx.compose.ui:ui", version.ref = "ui" }

#Compose
navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation-compose" }
#Dagger-Hilt
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }
hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hilt-compose" }
hilt-work = { group = "androidx.hilt", name = "hilt-work", version.ref = "hilt-work" }
hilt-work-compiler = { group = "androidx.hilt", name = "hilt-compiler", version.ref = "hilt-work" }

#Activity KTX for viewModels()
activity-ktx = { group = "androidx.activity", name = "activity-ktx", version.ref = "activity-ktx" }

#Lifecycle
lifecycle-extensions = { group = "androidx.lifecycle", name = "lifecycle-extensions", version.ref = "lifecycle-extensions" }
lifecycle-livedata-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "lifecycle-version" }
lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycle-version" }
lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "lifecycle-version" }
lifecycle-process = { group = "androidx.lifecycle", name = "lifecycle-process", version.ref = "lifecycle-version" }
lifecycle-common-java8 = { group = "androidx.lifecycle", name = "lifecycle-common-java8", version.ref = "lifecycle-version" }
runtime-livedata = { group = "androidx.compose.runtime", name = "runtime-livedata", version.ref = "runtime-livedata" }

#Coroutines
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }

#Splash
core-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "core-splashscreen" }

#Data Store
datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastore-preferences" }

#Lottie Animation
lottie-compose = { group = "com.airbnb.android", name = "lottie-compose", version.ref = "lottie-compose" }

#Coil Image Loading
coil-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil" }
coil-video = { group = "io.coil-kt", name = "coil-video", version.ref = "coil" }

#Download File
work-runtime-ktx = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "work-runtime-ktx" }

# PDFium
androidx-navigation-testing = { group = "androidx.navigation", name = "navigation-testing", version.ref = "navigationTesting" }
core = { group = "com.google.ar", name = "core", version.ref = "core" }
#android-pdf-viewer = { group = "com.github.barteksc", name = "android-pdf-viewer", version.ref = "android-pdf-viewer" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
jetbrainsKotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
